# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='cedula',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
