# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_remove_profesor_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre_completo',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
