# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
