# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='inicio',
            field=models.DateField(),
        ),
    ]
