# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representante',
            old_name='codigorep',
            new_name='id',
        ),
    ]
