# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(choices=[(False, 'Injustificada'), (True, 'Justificada')], default=False)),
                ('tipo', models.CharField(choices=[('F', 'Falta'), ('A', 'Atraso')], default='A', max_length=1)),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Inspector')),
            ],
        ),
    ]
