# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursoasignaturaestudiante', '0001_initial'),
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='asignaturaestudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cursoasignaturaestudiante.CursoAsignaturaEstudiante'),
            preserve_default=False,
        ),
    ]
