# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_incidencia_asignaturaestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('F', 'Falta'), ('A', 'Atraso')], default='F', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='incidencia',
            unique_together=set([('asignaturaestudiante', 'fecha', 'estado', 'tipo')]),
        ),
    ]
