# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0003_auto_20160701_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='asignaturaestudiante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cursoasignaturaestudiante.CursoAsignaturaEstudiante'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='revisado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.Inspector'),
        ),
    ]
