# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0004_auto_20160725_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidencia',
            unique_together=set([('asignaturaestudiante', 'fecha')]),
        ),
    ]
