# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0005_auto_20160731_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
