# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0006_incidencia_cedula_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='justificacion',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
