# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0007_incidencia_justificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='cedula_representante',
        ),
    ]
