# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0008_remove_incidencia_cedula_representante'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidencia',
            unique_together=set([]),
        ),
    ]
