# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0011_auto_20160907_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidencia',
            unique_together=set([('asignaturaestudiante', 'hora')]),
        ),
    ]
