# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20160820_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set([]),
        ),
    ]
