# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
        ('asignatura', '0001_initial'),
        ('curso', '0001_initial'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.Asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo.Periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cursoasignatura',
            unique_together=set([('asignatura', 'curso', 'periodo', 'profesor')]),
        ),
    ]
