# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoasignatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoasignatura',
            name='numero_horas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
