# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursoasignatura', '0002_cursoasignatura_numero_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoasignatura',
            options={'verbose_name': 'Asignatura'},
        ),
    ]
