# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursoasignatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes')], default='0', max_length=1)),
                ('hora', models.CharField(choices=[('1', 'Primera'), ('2', 'Segunda'), ('3', 'Tercera'), ('4', 'Cuarta'), ('5', 'Quinta'), ('6', 'Sexta'), ('7', 'S\xe9ptima'), ('8', 'Octava'), ('9', 'Novena')], default='1', max_length=1)),
                ('cursoasignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursoasignatura.CursoAsignatura')),
            ],
        ),
    ]
