# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.CharField(choices=[('1', '07:25 - 08:05'), ('2', '08:05 - 08:45'), ('3', '08:45 - 09:25'), ('4', '09:25 - 10:05'), ('5', '10:05 - 10:45'), ('6', '10:45 - 11:25'), ('7', '11:25 - 12:05'), ('8', '12:05 - 12:45'), ('9', '12:45 - 13:25'), ('10', '13:25 - 12:05')], default='1', max_length=1),
        ),
    ]
